### ISSUE TITLE
Install your editer in other web-site.

### ISSUE THREAD

**Issue by AnatoliyURL** [carstenschaefer/ImagerJs#9]
Hi, Carsten Schäfer. I'm have question. 

How do i can install your ImagerJs in my site? 

I followed guide  in wiki [https://github.com/carstenschaefer/ImagerJs/wiki/Getting-Started:-Standalone](url) , but this is... don't work.

In your guide indicates that we can easily connect [https://www.imagerjs.com/](url) but the URL [https://www.imagerjs.com/Home/Error?aspxerrorpath=/documentation/getting-started-standalone](url) is not valid.

Where to get the files: font-awesome/font-awesome.min.css , fonts/fontawesome-webfont.woff, imagerJs.min.css, imagerJs.min.js?

I'm sorry that asking a stupid question, but I'm not understand.

**Comment by srkela** [comment]
Hi there,

All required files you can find in the repository in examples folder.
You can find folders structure for default setup in [wiki page](https://github.com/carstenschaefer/ImagerJs/wiki/Getting-Started:-Standalone)
